version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        image: openeclass/app
        volumes:
            - app:/openeclass
            - ./config:/openeclass/config
            - ./courses:/openeclass/courses
            - ./video:/openeclass/video
        depends_on:
            - php
            - db
        ports:
            - "8080:80"
    php:
        build:
            context: .
            dockerfile: Dockerfile.phpfpm
        environment:
            MYSQL_ROOT_PASSWORD: eclassdbpassword #  The password of the database
            MYSQL_LOCATION: db                    # The location of the database
        image: openeclass/php
        volumes:
            - app:/openeclass
            - ./config:/openeclass/config
            - ./courses:/openeclass/courses
            - ./video:/openeclass/video
    db:   # The location of the database
        image: docker.io/mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: eclassdbpassword # The password of the database
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql

volumes:
    app:
